* Declarations
:PROPERTIES:
:export_file_name: declarations.txt
:END:

Including definitions, and items.

** Attributes

*** Normal
#+begin_test
#[foo(bar)]

#[foo]

#[test(should_fail_with = "howdy there")]

#[multiple] #[on a single line]

#['tag]
#[and stacked]

---

(attribute_item
  (content))
(attribute_item
  (content))
(attribute_item
  (content))
(attribute_item
  (content))
(attribute_item
  (content))
(attribute_item
  (content))
(attribute_item
  (content))
#+end_test

**** Invalid inner character
#+begin_test :error
#@[bad]
fn normal() {}
#+end_test

*** Degenerate
#+begin_test
#[   ]

#[oracle( )]

#[oracle(...)]

#[ leading, and space,      seperated  /with/  punctuation!!!,{}|!#_ () () ( ( ) () ( ]

---

(attribute_item
  (content))
(attribute_item
  (content))
(attribute_item
  (content))
(attribute_item
  (content))
#+end_test

** Modifiers

*** Visibility

**** Top-level
*************** TODO Are top-level naked visibility modifiers valid...?
*************** END

** Use

*** Simple

#+begin_test
use foo;
use foo::bar;
use foo::bar::lorem;
use foo::bar::lorem::ipsum;

---

(use_declaration
  tree: (identifier))
(use_declaration
  tree: (path
    scope: (identifier)
    name: (identifier)))
(use_declaration
  tree: (path
    scope: (path
      scope: (identifier)
      name: (identifier))
    name: (identifier)))
(use_declaration
  tree: (path
    scope: (path
      scope: (path
        scope: (identifier)
        name: (identifier))
      name: (identifier))
    name: (identifier)))
#+end_test

**** Trailing colons

No trailing colons allowed.

#+begin_test :error
use foo::;
#+end_test

#+begin_test :error
use foo::bar::;
#+end_test

*** Visibility

#+begin_test
pub use foo;
pub(crate) use foo;
pub use foo::bar::baz;

---

(use_declaration
  (visibility_modifier)
  tree: (identifier))
(use_declaration
  (visibility_modifier)
  tree: (identifier))
(use_declaration
  (visibility_modifier)
  tree: (path
    scope: (path
      scope: (identifier)
      name: (identifier))
    name: (identifier)))
#+end_test

*** Kind

#+begin_test
use crate::foo;
use dep::foo;
use super::foo;
use super::foo::bar::baz;

use foo::crate::bar;

---

(use_declaration
  tree: (path
    scope: (crate)
    name: (identifier)))
(use_declaration
  tree: (path
    scope: (dep)
    name: (identifier)))
(use_declaration
  tree: (path
    scope: (super)
    name: (identifier)))
(use_declaration
  tree: (path
    scope: (path
      scope: (path
        scope: (super)
        name: (identifier))
      name: (identifier))
    name: (identifier)))

(use_declaration
  tree: (path
    scope: (path
      scope: (identifier)
      name: (identifier))
    name: (identifier)))
#+end_test

*** List

**** Simple

#+begin_test
use foo::{};
use foo::{bar};
use foo::bar::baz::{lorem};

use foo::{bar, baz};
use foo::{bar, baz, };

use crate::{foo, bar};

---

(use_declaration
  tree: (path
    scope: (identifier)
    list: (use_list)))
(use_declaration
  tree: (path
    scope: (identifier)
    list: (use_list
      (identifier))))
(use_declaration
  tree: (path
    scope: (path
      scope: (path
        scope: (identifier)
        name: (identifier))
      name: (identifier))
    list: (use_list
      (identifier))))

(use_declaration
  tree: (path
    scope: (identifier)
    list: (use_list
      (identifier)
      (identifier))))
(use_declaration
  tree: (path
    scope: (identifier)
    list: (use_list
      (identifier)
      (identifier))))

(use_declaration
  tree: (path
    scope: (crate)
    list: (use_list
      (identifier)
      (identifier))))
#+end_test

**** Nesting

#+begin_test
use {foo::{a, b}, c, d};

use crate::bar::foo::{give::nested::{a, b}, and::more::{d, e::blah}, };

---

(use_declaration
  tree: (use_list
    (path
      scope: (identifier)
      list: (use_list
        (identifier)
        (identifier)))
    (identifier)
    (identifier)))

(use_declaration
  tree: (path
    scope: (path
      scope: (path
        scope: (crate)
        name: (identifier))
      name: (identifier))
    list: (use_list
      (path
        scope: (path
          scope: (identifier)
          name: (identifier))
        list: (use_list
          (identifier)
          (identifier)))
      (path
        scope: (path
          scope: (identifier)
          name: (identifier))
        list: (use_list
          (identifier)
          (path
            scope: (identifier)
            name: (identifier)))))))
#+end_test

**** Degenerate

Empty use lists are valid.
#+begin_test
use {};

---

(use_declaration
  tree: (use_list))
#+end_test

A path with no scope to an empty use list.
#+begin_test
use ::{};

---

(use_declaration
  tree: (path
    list: (use_list)))
#+end_test

Lone comma is the same as an empty use list, as are multiple empty nested use lists.
#+begin_test
use {,};
use {{},{},{}};

---

(use_declaration
  tree: (use_list))
(use_declaration
  tree: (use_list
    (use_list)
    (use_list)
    (use_list)))
#+end_test

**** Trailing colons

#+begin_test :error
use foo::{}::;
#+end_test

#+begin_test :error
use foo::bar::{}::;
#+end_test

**** Multiple lists

#+begin_test :error
use foo::{}::{};
#+end_test

#+begin_test :error
use foo::bar::{}::{};
#+end_test

**** Non-plain subtree

Cannot have any PathKind in use subtree.

*************** TODO Do I NEED to get these tests passing? This could be too minute for tree-sitter
Like how ordering of the modifiers etc isn't really viable.
*************** END

use foo::{crate::bar};

use foo::{dep::bar};

use foo::{super::bar};

*** Alias

TODO: is =use foo::bar::{lorem as ipsum, dolor as swag};= allowed in Noir?

#+begin_test
use foo as bar;
use foo::bar as lorem;
use foo::bar::lorem as ipsum;

---

(use_declaration
  tree: (use_alias
    scope: (identifier)
    alias: (identifier)))
(use_declaration
  tree: (use_alias
    scope: (path
      scope: (identifier)
      name: (identifier))
    alias: (identifier)))
(use_declaration
  tree: (use_alias
    scope: (path
      scope: (path
        scope: (identifier)
        name: (identifier))
      name: (identifier))
    alias: (identifier)))
#+end_test

** ModOrContract

*** Simple
#+begin_test
mod foo;
contract foo;

mod bar {}
contract bar {}

---

(module_or_contract_item
  name: (identifier))
(module_or_contract_item
  name: (identifier))

(module_or_contract_item
  name: (identifier)
  body: (item_list))
(module_or_contract_item
  name: (identifier)
  body: (item_list))
#+end_test

*** Nested
#+begin_test
mod foo { mod bar; }
contract foo { contract bar; }

contract foo { mod bar {} }
mod foo {
  mod bar {}
  mod lorem {}
}

---

(module_or_contract_item
  name: (identifier)
  body: (item_list
    (module_or_contract_item
      name: (identifier))))
(module_or_contract_item
  name: (identifier)
  body: (item_list
    (module_or_contract_item
      name: (identifier))))

(module_or_contract_item
  name: (identifier)
  body: (item_list
    (module_or_contract_item
      name: (identifier)
      body: (item_list))))
(module_or_contract_item
  name: (identifier)
  body: (item_list
    (module_or_contract_item
      name: (identifier)
      body: (item_list))
    (module_or_contract_item
      name: (identifier)
      body: (item_list))))
#+end_test

*** Visibility
#+begin_test
pub mod foo;
pub(crate) contract foo;

pub contract foo { pub mod bar; }
pub contract foo { pub(crate) mod bar {} }

---

(module_or_contract_item
  (visibility_modifier)
  name: (identifier))
(module_or_contract_item
  (visibility_modifier)
  name: (identifier))

(module_or_contract_item
  (visibility_modifier)
  name: (identifier)
  body: (item_list
    (module_or_contract_item
      (visibility_modifier)
      name: (identifier))))
(module_or_contract_item
  (visibility_modifier)
  name: (identifier)
  body: (item_list
    (module_or_contract_item
      (visibility_modifier)
      name: (identifier)
      body: (item_list))))
#+end_test

*** No path in name
#+begin_test :error
mod foo::bar;
#+end_test

#+begin_test :error
mod foo::bar {};
#+end_test

#+begin_test :error
mod foo::bar { mod foo::bar };
#+end_test

** Struct

*** Simple
#+begin_test
struct foo;
struct foo {}
pub struct foo;
pub(crate) struct foo{}

---

(struct_item
  name: (identifier))
(struct_item
  name: (identifier)
  body: (struct_field_list))
(struct_item
  (visibility_modifier)
  name: (identifier))
(struct_item
  (visibility_modifier)
  name: (identifier)
  body: (struct_field_list))
#+end_test

*** Fields
#+begin_test
struct foo {
  x: i32,
  pub y: Field,
  pub(crate) yolo: (),
}

---

(struct_item
  name: (identifier)
  body: (struct_field_list
    (struct_field_item
      name: (identifier)
      type: (primitive_type))
    (struct_field_item
      (visibility_modifier)
      name: (identifier)
      type: (primitive_type))
    (struct_field_item
      (visibility_modifier)
      name: (identifier)
      type: (unit_type))))
#+end_test

*** Generic
#+begin_test :skip
struct foo<A, let B: u32> {}

---

TODO
#+end_test

*** Degenerate
#+begin_test
struct foo {,}
struct foo {x:i32,}
struct foo {pub(crate)x:(),}

---

(struct_item
  name: (identifier)
  body: (struct_field_list))
(struct_item
  name: (identifier)
  body: (struct_field_list
    (struct_field_item
      name: (identifier)
      type: (primitive_type))))
(struct_item
  name: (identifier)
  body: (struct_field_list
    (struct_field_item
      (visibility_modifier)
      name: (identifier)
      type: (unit_type))))
#+end_test

*** Unclosed

#+begin_test :error
struct foo {
#+end_test

** Impl

*** Simple
#+begin_test :skip
impl foo {}

---

(impl_item
  name: (identifier))
#+end_test

** Trait
x

** Global
x

** TypeAlias
x

** Function

*************** TODO The Functions subtree can be flattened out so modifiers test all things modifiers are applicable to instead of ONLY in the context of functions
*************** END

Need to test:
  - Return visibility (i.e. Visibility headline)

*** Definitions
#+begin_test :extract :skip
fn hello_world() {}

fn foo() {}

fn before123four_five_678() {}

---

(function_definition
  name: (identifier)
  (parameter_list)
  (block))

(function_definition
  name: (identifier)
  (parameter_list)
  (block))

(function_definition
  name: (identifier)
  (parameter_list)
  (block))
#+end_test

**** Starting with integer literal
#+begin_test :error :extract
fn 123_not_okay() {}
#+end_test

**** Starting with negation operator
#+begin_test :error :extract
fn !nope() {}
#+end_test

**** Missing parameter list
#+begin_test :error :extract
fn nah {}
#+end_test

**** Missing block expression
#+begin_test :error :extract
fn silly()
#+end_test

*** Modifiers
#+begin_test :skip
pub fn one() {}
pub(crate) fn two() {}

unconstrained fn three() {}
pub unconstrained fn four() {}
pub(crate) unconstrained fn five() {}

comptime fn six() {}
pub(crate) comptime fn seven() {}

pub unconstrained comptime fn eight() {}
pub(crate) unconstrained comptime fn nine() {}

---

(function_definition
  (visibility_modifier)
  name: (identifier)
  (parameter_list)
  (block))
(function_definition
  (visibility_modifier)
  name: (identifier)
  (parameter_list)
  (block))

(function_definition
  (function_modifiers)
  name: (identifier)
  (parameter_list)
  (block))
(function_definition
  (visibility_modifier)
  (function_modifiers)
  name: (identifier)
  (parameter_list)
  (block))
(function_definition
  (visibility_modifier)
  (function_modifiers)
  name: (identifier)
  (parameter_list)
  (block))

(function_definition
  (function_modifiers)
  name: (identifier)
  (parameter_list)
  (block))
(function_definition
  (visibility_modifier)
  (function_modifiers)
  name: (identifier)
  (parameter_list)
  (block))

(function_definition
  (visibility_modifier)
  (function_modifiers)
  name: (identifier)
  (parameter_list)
  (block))
(function_definition
  (visibility_modifier)
  (function_modifiers)
  name: (identifier)
  (parameter_list)
  (block))
#+end_test

**** Visibility position
#+begin_test :error
fn pub one() {}
#+end_test

#+begin_test :error
fn pub(crate) one() {}
#+end_test

**** Visibility repeated
#+begin_test :error
fn pub pub one() {}
#+end_test

#+begin_test :error
fn pub(crate) pub one() {}
#+end_test

**** Unconstrained position
#+begin_test :error
fn unconstrained pub one() {}
#+end_test

#+begin_test :error
unconstrained pub fn one() {}
#+end_test

**** Unconstrained repeated
#+begin_test :error
fn unconstrained unconstrained one() {}
#+end_test

* Statements
:PROPERTIES:
:export_file_name: statements.txt
:END:

** Break
#+begin_test
global foo1 = { break; };

---

(global_item
  name: (identifier)
  (block
    (break_statement)))
#+end_test

* Expressions
:PROPERTIES:
:export_file_name: expressions.txt
:END:

** Literal

*** String
#+begin_test
global foo = "";
global foo = "\\";

global bar = "hello";
global bar = "hello\"escaped\"";

global lorem = "hello
multiline
        with scapes and *&!@#%!@#(&!#())
some escapes \r \n \"nested string \r\n\"
blah";

---

(global_item
  name: (identifier)
  (str_literal))
(global_item
  name: (identifier)
  (str_literal
    (escape_sequence)))

(global_item
  name: (identifier)
  (str_literal
    (str_content)))
(global_item
  name: (identifier)
  (str_literal
    (str_content)
    (escape_sequence)
    (str_content)
    (escape_sequence)))

(global_item
  name: (identifier)
  (str_literal
    (str_content)
    (escape_sequence)
    (str_content)
    (escape_sequence)
    (str_content)
    (escape_sequence)
    (str_content)
    (escape_sequence)
    (escape_sequence)
    (escape_sequence)
    (str_content)))
#+end_test

*** Raw string
#+begin_test
global foo = r"minimal";
global foo = r##"foo"##;
global foo = r"hi\there";
global foo = r"r#r";

---

(global_item
  name: (identifier)
  (raw_str_literal
    (str_content)))
(global_item
  name: (identifier)
  (raw_str_literal
    (str_content)))
(global_item
  name: (identifier)
  (raw_str_literal
    (str_content)))
(global_item
  name: (identifier)
  (raw_str_literal
    (str_content)))
#+end_test

**** Double quote
#+begin_test
global foo = r#""foo""#;

---

(global_item
  name: (identifier)
  (raw_str_literal
    (str_content)))
#+end_test

**** Complex
#+begin_test
global foo = r#"minimal\"escapes\"are\nall\rignored

in "here""#;

global bar = r####"foo ##"blah"##"####;

---

(global_item
  name: (identifier)
  (raw_str_literal
    (str_content)))
(global_item
  name: (identifier)
  (raw_str_literal
    (str_content)))
#+end_test

**** Pounds balanced
#+begin_test :error
global foo = r###"unbalanced"##;
#+end_test

**** Pounds nested magnitude
#+begin_test :error
global foo = r##"can only nest with ####"fewer pounds"#### blah"##;
#+end_test

**** Quote no pounds
#+begin_test :error
global foo = r"you need at least 1 pound in delimiter to have quotes _within_ the string like: " <- that even if you try: \" <- that also";
#+end_test

*** Format string
#+begin_test
global foo = f"";
global foo = f"\\";

global bar = f"hello";
global bar = f"escape sequences are \n literal \t";

---

(global_item
  name: (identifier)
  (fmt_str_literal))
(global_item
  name: (identifier)
  (fmt_str_literal
    (str_content)))

(global_item
  name: (identifier)
  (fmt_str_literal
    (str_content)))
(global_item
  name: (identifier)
  (fmt_str_literal
    (str_content)))
#+end_test

**** Quote escape
#+begin_test :error
global foo = f"no \"quotes\" can be escaped in a format string";
#+end_test

*** Quasiquote
#+begin_test :skip
global foo = quote { 1 };

---

(global_item
  name: (identifier)
  (quote_expression))
#+end_test

*** Array expression

*************** TODO If replace =2= with =true= it still parses but that's not a valid atom here
*************** END

**** Standard
#+begin_test
global foo1 = [true, false, 1, 2, 3];
global foo2 = [1 + 1, 2 + 2];

---

(global_item
  name: (identifier)
  (array_expression
    (bool_literal)
    (bool_literal)
    (int_literal)
    (int_literal)
    (int_literal)))
(global_item
  name: (identifier)
  (array_expression
    (binary_expression
      left: (int_literal)
      right: (int_literal))
    (binary_expression
      left: (int_literal)
      right: (int_literal))))
#+end_test

***** Degenerate
#+begin_test
global foo1 = [1,];
global foo2 = [,];

---

(global_item
  name: (identifier)
  (array_expression
    (int_literal)))
(global_item
  name: (identifier)
  (array_expression))
#+end_test

**** Repeated
#+begin_test
global foo1 = [1; 2];
global foo2 = [1; 2 + 3];

global bar1 = [true; 1 + 2 - 3];
global bar2 = ["foo"; -5];
global bar4 = [f"bar"; 1];

global lorem1 = [false; (1)];
global lorem2 = ["foo"; (-1 + 5)];
global lorem3 = [1; -(2 + 2)];

---

(global_item
  name: (identifier)
  (array_expression
    (int_literal)
    length: (int_literal)))
(global_item
  name: (identifier)
  (array_expression
    (int_literal)
    length: (binary_expression
      left: (int_literal)
      right: (int_literal))))

(global_item
  name: (identifier)
  (array_expression
    (bool_literal)
    length: (binary_expression
      left: (binary_expression
        left: (int_literal)
        right: (int_literal))
      right: (int_literal))))
(global_item
  name: (identifier)
  (array_expression
    (str_literal
      (str_content))
    length: (unary_expression
      (int_literal))))
(global_item
  name: (identifier)
  (array_expression
    (fmt_str_literal
      (str_content))
    length: (int_literal)))

(global_item
  name: (identifier)
  (array_expression
    (bool_literal)
    length: (parenthesized_expression
      (int_literal))))
(global_item
  name: (identifier)
  (array_expression
    (str_literal
      (str_content))
    length: (parenthesized_expression
      (binary_expression
        left: (unary_expression
          (int_literal))
        right: (int_literal)))))
(global_item
  name: (identifier)
  (array_expression
    (int_literal)
    length: (unary_expression
      (parenthesized_expression
        (binary_expression
          left: (int_literal)
          right: (int_literal))))))
#+end_test

***** Degenerate
#+begin_test
global foo1 = [1; --5];
global foo2 = [true; --5 + 1];

---

(global_item
  name: (identifier)
  (array_expression
    (int_literal)
    length: (unary_expression
      (unary_expression
        (int_literal)))))
(global_item
  name: (identifier)
  (array_expression
    (bool_literal)
    length: (binary_expression
      left: (unary_expression
        (unary_expression
          (int_literal)))
      right: (int_literal))))
#+end_test

**** TODO Path
#+begin_test :skip
global foo = [1; N];
global foo = [1; foo::bar];
#+end_test

*** Slice expression

Only really need to test =&= prefix, rest is array expression.

**** Standard
#+begin_test
global foo1 = &[1];
global foo1 = &     [1];

---

(global_item
  name: (identifier)
  (slice_expression
    (array_expression
      (int_literal))))
(global_item
  name: (identifier)
  (slice_expression
    (array_expression
      (int_literal))))
#+end_test

**** Repeated
#+begin_test
global foo1 = &[1; 2];
global foo2 = &       [1; 2];

---

(global_item
  name: (identifier)
  (slice_expression
    (array_expression
      (int_literal)
      length: (int_literal))))
(global_item
  name: (identifier)
  (slice_expression
    (array_expression
      (int_literal)
      length: (int_literal))))
#+end_test

*** Block expression
TODO (after statements)

** Binary

*** Simple
#+begin_test
global foo1 = 1 * 1;
global foo2 = 1 / 1;
global foo3 = 1 % 1;

global bar1 = 1 + 1;
global bar2 = 1 - 1;

global baz1 = 1 << 1;
global baz2 = 1 >> 1;

global lorem1 = 1 < 1;
global lorem2 = 1 <= 1;
global lorem3 = 1 > 1;
global lorem4 = 1 >= 1;

global ipsum = 1 ^ 1;

global dolor = 1 & 1;

global etut = 1 | 1;

global boo1 = 1 | 1;
global boo2 = 1 | 1;

---

(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))
(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))
(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))

(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))
(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))

(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))
(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))

(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))
(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))
(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))
(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))

(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))

(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))

(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))

(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))
(global_item
  name: (identifier)
  (binary_expression
    left: (int_literal)
    right: (int_literal)))
#+end_test

*** Precedence

**** Same

So =a * x / y % z= equivalent to =((a * x) / y) % z=

#+begin_test
global foo = false * 2 / 3 % true;

---

(global_item
  name: (identifier)
  (binary_expression
    left: (binary_expression
      left: (binary_expression
        left: (bool_literal)
        right: (int_literal))
      right: (int_literal))
    right: (bool_literal)))
#+end_test

**** Different

So =x + y - z= equivalent to =(x + y) - z=

#+begin_test
global bar = 1 + true - 3;

global foo = false * 2 / 3 % true  +  false / 5   -   10 * true;

---

(global_item
  name: (identifier)
  (binary_expression
    left: (binary_expression
      left: (int_literal)
      right: (bool_literal))
    right: (int_literal)))

(global_item
  name: (identifier)
  (binary_expression
    left: (binary_expression
      left: (binary_expression
        left: (binary_expression
          left: (binary_expression
            left: (bool_literal)
            right: (int_literal))
          right: (int_literal))
        right: (bool_literal))

      right: (binary_expression
        left: (bool_literal)
        right: (int_literal)))

    right: (binary_expression
      left: (int_literal)
      right: (bool_literal))))
#+end_test

*************** TODO Even more nested precedence levels?
i.e. =<<= and =>>= etc all the way down to ==== and =!==.
*************** END

*** Parenthesized

TODO

** Unary

TODO

* Types
:PROPERTIES:
:export_file_name: types.txt
:END:

** Unit
#+begin_test :skip
type Foo = ();

---

(source_file
  (unit_type))
#+end_test

** Type expressions

*** Literal
#+begin_test :skip
global foo = [u8; 69];

---

(global_item
  name: (identifier)
  )
#+end_test

*** Binary
#+begin_test :skip
global foo = [u8; 1 + 2];
#+end_test

* Literals
:PROPERTIES:
:export_file_name: literals.txt
:END:

* Extras
:PROPERTIES:
:export_file_name: extras.txt
:END:

** Comments

*** Line

**** No doc-style

#+begin_test :comments link
// Foobar
// Lorem
//Whitespace at comment glue-tokens doesn't matter
// Comments cannot be nested // So this line // Is a single comment // Not four
//// Four slashes is also a normal line comment!
//
//             Big leading whitespace

// !Not a doc comment because there's a space between the // and !

// Lone

// Wolf

---

(line_comment)
(line_comment)
(line_comment)
(line_comment)
(line_comment)
(line_comment)
(line_comment)
(line_comment)
(line_comment)
(line_comment)
#+end_test

**** Inner doc-style

#+begin_test
//! Foobar inner line doc comment
//!No whitespace at glue-token
//! No nested //! Line doc /// Comments // Or normal
//!         Big leading
//!

//! Lone

//!         ~~~~~~Wolf~~~~~~!**!#$%#!^&@%$!#(!#^!@&(!@*&@!)) (lots of ascii spam)

---

(line_comment
  style: (inner_doc_style)
  content: (doc_comment))
(line_comment
  style: (inner_doc_style)
  content: (doc_comment))
(line_comment
  style: (inner_doc_style)
  content: (doc_comment))
(line_comment
  style: (inner_doc_style)
  content: (doc_comment))
(line_comment
  style: (inner_doc_style)
  content: (doc_comment))
(line_comment
  style: (inner_doc_style)
  content: (doc_comment))
(line_comment
  style: (inner_doc_style)
  content: (doc_comment))
#+end_test

**** Outer doc-style

#+begin_test
/// Foobar outer line doc comment
///No whitespace at glue-token
/// No nested /// Line doc //! Comments // Or normal
///         Big leading
///

/// Lone

///         ~~~~~~Wolf~~~~~~!**!#$%#!^&@%$!#(!#^!@&(!@*&@!)) (lots of ascii spam)

---

(line_comment
  style: (outer_doc_style)
  content: (doc_comment))
(line_comment
  style: (outer_doc_style)
  content: (doc_comment))
(line_comment
  style: (outer_doc_style)
  content: (doc_comment))
(line_comment
  style: (outer_doc_style)
  content: (doc_comment))
(line_comment
  style: (outer_doc_style)
  content: (doc_comment))
(line_comment
  style: (outer_doc_style)
  content: (doc_comment))
(line_comment
  style: (outer_doc_style)
  content: (doc_comment))
#+end_test

*** Block

**** No doc-style

#+begin_test
/* single line block comment */

/*whitespace doesn't matter*/

/*                big        padding           */

/* multi line
block comment */

/* lots of ** asterisks * */

/**/

---

(block_comment)
(block_comment)
(block_comment)
(block_comment)
(block_comment)
(block_comment)
#+end_test

***** Degenerate

An empty outer-style block comment is just a normal block comment.

#+begin_test
/***/

---

(block_comment)
#+end_test

Outer-style block comments must have exactly this starting delimiter =/**=, so =/****/= is not an outer-style block comment with content =*= but rather a normal block comment.

#+begin_test
/****/

---

(block_comment)
#+end_test

Remaining degenerate.

#+begin_test
/* n *//***/

/*         ~~~~~~Wolf~~~~~~!**!#$%#!^&@%$!#(!#^!@&(!@*&@!)) (lots of ascii spam)
//! lorem
// foo
/// bar
*/

---

(block_comment)
(block_comment)
(block_comment)
#+end_test

***** Nested

#+begin_test
/* single line /* nested /* block */ comment */ */

/* no nesting kids /** */ /**/ /***/ /*!*/ /*! */ */

---

(block_comment)
(block_comment)
#+end_test

***** Unmatched

Simple.
#+begin_test :error
/* unmatched single line
#+end_test

Nested.
#+begin_test :error
/* unmatched /* nested comment */
#+end_test

Multiline nested.
#+begin_test :error
/* unmatched /*
multiline /* nested
comment */ */
#+end_test

**** Inner doc-style

#+begin_test
/*! single */

/*!whitespace doesn't matter*/

/*!    big   padding    */

/*! single /*! nested /* block */ comment */ */

/*! multi line
block comment */

/*! lots of ** asterisks * */

/*! no nesting kids /** */ /**/ /***/ /*!*/ /*! */ */

/*!!*/

/*!         ~~~~~~Wolf~~~~~~!**!#$%#!^&@%$!#(!#^!@&(!@*&@!)) (lots of ascii spam)
//! nope
// foo
/// bar
*/

---

(block_comment
  style: (inner_doc_style)
  content: (doc_comment))
(block_comment
  style: (inner_doc_style)
  content: (doc_comment))
(block_comment
  style: (inner_doc_style)
  content: (doc_comment))
(block_comment
  style: (inner_doc_style)
  content: (doc_comment))
(block_comment
  style: (inner_doc_style)
  content: (doc_comment))
(block_comment
  style: (inner_doc_style)
  content: (doc_comment))
(block_comment
  style: (inner_doc_style)
  content: (doc_comment))
(block_comment
  style: (inner_doc_style)
  content: (doc_comment))
(block_comment
  style: (inner_doc_style)
  content: (doc_comment))
#+end_test

***** Empty

Empty inner-style block comments are possible.
#+begin_test
/*!*/

---

(block_comment
  style: (inner_doc_style))
#+end_test

**** Outer doc-style

#+begin_test
/** single */

/**whitespace doesn't matter*/

/**    big   padding    */

/** single /** nested /* block */ comment */ */

/** multi line
block comment */

/** lots of ** asterisks * */

/** no nesting kids /** */ /**/ /***/ /*!*/ /*! */ */

/**         ~~~~~~Wolf~~~~~~!**!#$%#!^&@%$!#(!#^!@&(!@*&@!)) (lots of ascii spam)
//! nope
// foo
/// bar
*/

---

(block_comment
  style: (outer_doc_style)
  content: (doc_comment))
(block_comment
  style: (outer_doc_style)
  content: (doc_comment))
(block_comment
  style: (outer_doc_style)
  content: (doc_comment))
(block_comment
  style: (outer_doc_style)
  content: (doc_comment))
(block_comment
  style: (outer_doc_style)
  content: (doc_comment))
(block_comment
  style: (outer_doc_style)
  content: (doc_comment))
(block_comment
  style: (outer_doc_style)
  content: (doc_comment))
(block_comment
  style: (outer_doc_style)
  content: (doc_comment))
#+end_test

***** Minimal

Empty outer-style block comments are not possible, must be exactly the prefix =/**= followed by any non =*= character and then the closing delimiter =*/=.

#+begin_test
/** */
/**x*/
/**!*/

---

(block_comment
  style: (outer_doc_style)
  content: (doc_comment))
(block_comment
  style: (outer_doc_style)
  content: (doc_comment))
(block_comment
  style: (outer_doc_style)
  content: (doc_comment))
#+end_test

*************** TODO Logic for :extract
This would call the noir frontend parser, e.g. say parse_program and vaidate correct syntax too. Might be overengineering so only do this after grammar is completed and refined a bit (i.e. usable in editors, helix, neovim, emacs).
*************** END

TODO: Default visibility in this file should be outline only (all headings visible but not their content), and all property drawers folded.
